"""
Gerber File Generator

Generates RS-274X Gerber files for PCB manufacturing:
- Copper layers (top, bottom, inner)
- Solder mask layers
- Silkscreen layers
- Solder paste layers
- Assembly layers
"""

import logging
from typing import Dict, List, Tuple, Optional
from datetime import datetime
from pathlib import Path

try:
    from backend.geometry.placement import Placement
    from backend.geometry.component import Component
except ImportError:
    from src.backend.geometry.placement import Placement
    from src.backend.geometry.component import Component

logger = logging.getLogger(__name__)


class GerberGenerator:
    """
    Generate RS-274X Gerber files for PCB manufacturing.
    
    Supports:
    - All copper layers
    - Solder mask
    - Silkscreen
    - Solder paste
    - Assembly drawings
    """
    
    def __init__(self):
        """Initialize Gerber generator."""
        self.layers = {
            "F.Cu": "Top Copper",
            "B.Cu": "Bottom Copper",
            "F.SilkS": "Top Silkscreen",
            "B.SilkS": "Bottom Silkscreen",
            "F.Mask": "Top Solder Mask",
            "B.Mask": "Bottom Solder Mask",
            "F.Paste": "Top Solder Paste",
            "B.Paste": "Bottom Solder Paste"
        }
    
    def generate_all_layers(
        self,
        placement: Placement,
        output_dir: str,
        board_name: str = "board"
    ) -> Dict[str, str]:
        """
        Generate all Gerber layers.
        
        Args:
            placement: Placement with components and traces
            output_dir: Output directory
            board_name: Board name (used in filenames)
        
        Returns:
            Dictionary mapping layer names to file paths
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        generated_files = {}
        
        # Generate copper layers
        if "F.Cu" in self.layers:
            top_copper = self.generate_copper_layer(placement, "F.Cu")
            filename = f"{board_name}-F_Cu.gbr"
            filepath = output_path / filename
            filepath.write_text(top_copper)
            generated_files["F.Cu"] = str(filepath)
        
        if "B.Cu" in self.layers:
            bottom_copper = self.generate_copper_layer(placement, "B.Cu")
            filename = f"{board_name}-B_Cu.gbr"
            filepath = output_path / filename
            filepath.write_text(bottom_copper)
            generated_files["B.Cu"] = str(filepath)
        
        # Generate solder mask layers
        top_mask = self.generate_solder_mask(placement, "F.Mask")
        filename = f"{board_name}-F_Mask.gbr"
        filepath = output_path / filename
        filepath.write_text(top_mask)
        generated_files["F.Mask"] = str(filepath)
        
        bottom_mask = self.generate_solder_mask(placement, "B.Mask")
        filename = f"{board_name}-B_Mask.gbr"
        filepath = output_path / filename
        filepath.write_text(bottom_mask)
        generated_files["B.Mask"] = str(filepath)
        
        # Generate silkscreen layers
        top_silk = self.generate_silkscreen(placement, "F.SilkS")
        filename = f"{board_name}-F_SilkS.gbr"
        filepath = output_path / filename
        filepath.write_text(top_silk)
        generated_files["F.SilkS"] = str(filepath)
        
        bottom_silk = self.generate_silkscreen(placement, "B.SilkS")
        filename = f"{board_name}-B_SilkS.gbr"
        filepath = output_path / filename
        filepath.write_text(bottom_silk)
        generated_files["B.SilkS"] = str(filepath)
        
        # Generate solder paste layers
        top_paste = self.generate_solder_paste(placement, "F.Paste")
        filename = f"{board_name}-F_Paste.gbr"
        filepath = output_path / filename
        filepath.write_text(top_paste)
        generated_files["F.Paste"] = str(filepath)
        
        logger.info(f"Generated {len(generated_files)} Gerber files")
        return generated_files
    
    def generate_copper_layer(
        self,
        placement: Placement,
        layer: str
    ) -> str:
        """
        Generate copper layer Gerber file.
        
        Args:
            placement: Placement with components and traces
            layer: Layer name (F.Cu, B.Cu, etc.)
        
        Returns:
            Gerber file content (RS-274X format)
        """
        lines = []
        
        # Gerber header
        lines.append("G04 Generated by Dielectric PCB Design Platform*")
        lines.append(f"G04 Layer: {layer}*")
        lines.append(f"G04 Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
        lines.append("%FSLAX26Y26*%")  # Format: 2.6 format, absolute, X and Y
        lines.append("%MOMM*%")  # Unit: millimeters
        lines.append("G04 APERTURE LIST*")
        lines.append("%ADD10C,0.200000*%")  # Aperture 10: Circle, 0.2mm
        lines.append("%ADD11C,0.500000*%")  # Aperture 11: Circle, 0.5mm
        lines.append("%ADD12R,0.200000X0.200000*%")  # Aperture 12: Rectangle
        lines.append("G04 APERTURE END*")
        lines.append("G04*")
        lines.append("G70*")  # Set to inches (will convert)
        lines.append("G90*")  # Absolute coordinates
        lines.append("G04*")
        
        # Board outline
        board = placement.board
        lines.append("G04 Board Outline*")
        lines.append(f"G04 X{board.width:.6f} Y{board.height:.6f}*")
        
        # Components (pads)
        lines.append("G04 Component Pads*")
        for comp_name, comp in placement.components.items():
            # Convert to Gerber coordinates (mm to format units)
            x_mm = comp.x
            y_mm = comp.y
            
            # Pad (simplified - would use actual footprint)
            lines.append(f"D11*")  # Select aperture 11
            lines.append(f"X{x_mm*1000000:.0f}Y{y_mm*1000000:.0f}D03*")  # Flash pad
        
        # Traces (if available in placement)
        if hasattr(placement, 'traces') and placement.traces:
            lines.append("G04 Traces*")
            for trace in placement.traces:
                if trace.get("layer") == layer:
                    start = trace["start_position"]
                    end = trace["end_position"]
                    width = trace.get("width", 0.2)
                    
                    # Select aperture based on width
                    aperture = 10 if width < 0.3 else 11
                    lines.append(f"D{aperture}*")
                    
                    # Draw trace
                    lines.append(f"X{start[0]*1000000:.0f}Y{start[1]*1000000:.0f}D02*")  # Move
                    lines.append(f"X{end[0]*1000000:.0f}Y{end[1]*1000000:.0f}D01*")  # Draw
        
        # Footer
        lines.append("M02*")  # End of program
        
        return "\n".join(lines)
    
    def generate_solder_mask(
        self,
        placement: Placement,
        layer: str
    ) -> str:
        """
        Generate solder mask layer.
        
        Solder mask exposes pads and vias (inverse of copper).
        """
        lines = []
        
        lines.append("G04 Generated by Dielectric - Solder Mask*")
        lines.append(f"G04 Layer: {layer}*")
        lines.append("%FSLAX26Y26*%")
        lines.append("%MOMM*%")
        lines.append("%ADD10C,0.200000*%")
        lines.append("G70*")
        lines.append("G90*")
        
        # Solder mask openings (pads and vias)
        for comp_name, comp in placement.components.items():
            x_mm = comp.x
            y_mm = comp.y
            
            # Solder mask opening (slightly larger than pad)
            lines.append("D10*")
            lines.append(f"X{x_mm*1000000:.0f}Y{y_mm*1000000:.0f}D03*")
        
        lines.append("M02*")
        
        return "\n".join(lines)
    
    def generate_silkscreen(
        self,
        placement: Placement,
        layer: str
    ) -> str:
        """
        Generate silkscreen layer.
        
        Contains component designators and outlines.
        """
        lines = []
        
        lines.append("G04 Generated by Dielectric - Silkscreen*")
        lines.append(f"G04 Layer: {layer}*")
        lines.append("%FSLAX26Y26*%")
        lines.append("%MOMM*%")
        lines.append("%ADD10C,0.100000*%")  # Smaller aperture for text
        lines.append("G70*")
        lines.append("G90*")
        
        # Component designators
        for comp_name, comp in placement.components.items():
            x_mm = comp.x
            y_mm = comp.y
            
            # Component outline (simplified)
            width = comp.width
            height = comp.height
            
            # Draw rectangle outline
            lines.append("D10*")
            # Top edge
            lines.append(f"X{(x_mm-width/2)*1000000:.0f}Y{(y_mm+height/2)*1000000:.0f}D02*")
            lines.append(f"X{(x_mm+width/2)*1000000:.0f}Y{(y_mm+height/2)*1000000:.0f}D01*")
            # Right edge
            lines.append(f"X{(x_mm+width/2)*1000000:.0f}Y{(y_mm-height/2)*1000000:.0f}D01*")
            # Bottom edge
            lines.append(f"X{(x_mm-width/2)*1000000:.0f}Y{(y_mm-height/2)*1000000:.0f}D01*")
            # Left edge
            lines.append(f"X{(x_mm-width/2)*1000000:.0f}Y{(y_mm+height/2)*1000000:.0f}D01*")
        
        lines.append("M02*")
        
        return "\n".join(lines)
    
    def generate_solder_paste(
        self,
        placement: Placement,
        layer: str
    ) -> str:
        """
        Generate solder paste layer.
        
        Used for SMT component assembly.
        """
        lines = []
        
        lines.append("G04 Generated by Dielectric - Solder Paste*")
        lines.append(f"G04 Layer: {layer}*")
        lines.append("%FSLAX26Y26*%")
        lines.append("%MOMM*%")
        lines.append("%ADD10C,0.200000*%")
        lines.append("G70*")
        lines.append("G90*")
        
        # Solder paste openings (only for SMT components)
        for comp_name, comp in placement.components.items():
            # Check if SMT (simplified - would check footprint)
            if comp.height < 2.0:  # SMT components are typically <2mm height
                x_mm = comp.x
                y_mm = comp.y
                
                lines.append("D10*")
                lines.append(f"X{x_mm*1000000:.0f}Y{y_mm*1000000:.0f}D03*")
        
        lines.append("M02*")
        
        return "\n".join(lines)

