"""
Netlist Generator

Generates netlists from PCB placement:
- KiCad netlist format
- SPICE netlist
- Generic netlist format
"""

import logging
from typing import Dict, List

try:
    from backend.geometry.placement import Placement
except ImportError:
    from src.backend.geometry.placement import Placement

logger = logging.getLogger(__name__)


class NetlistGenerator:
    """
    Generate netlists from PCB placement.
    
    Supports:
    - KiCad netlist format
    - SPICE netlist
    - Generic formats
    """
    
    def generate_kicad_netlist(self, placement: Placement) -> str:
        """
        Generate KiCad netlist format.
        
        Args:
            placement: Placement with components and nets
        
        Returns:
            KiCad netlist content
        """
        lines = []
        lines.append("(export (version D)")
        lines.append("  (design")
        lines.append(f'    (source "{placement.board.name or "board"}")')
        lines.append("    (date \"\")")
        lines.append("    (tool \"Dielectric\")")
        lines.append("  )")
        lines.append("  (components")
        
        # Components
        for comp_name, comp in placement.components.items():
            lines.append(f"    (comp (ref {comp_name})")
            lines.append(f"      (value {comp.value or comp_name})")
            lines.append(f"      (footprint {comp.package or 'UNKNOWN'})")
            lines.append("    )")
        
        lines.append("  )")
        lines.append("  (nets")
        
        # Nets
        for net_name, net in placement.nets.items():
            lines.append(f"    (net (code {net_name}) (name \"{net_name}\")")
            
            for comp_ref, pad_name in net.pins:
                lines.append(f"      (node (ref {comp_ref}) (pin {pad_name}))")
            
            lines.append("    )")
        
        lines.append("  )")
        lines.append(")")
        
        return "\n".join(lines)
    
    def generate_spice_netlist(self, placement: Placement) -> str:
        """
        Generate SPICE netlist format.
        
        Args:
            placement: Placement with components and nets
        
        Returns:
            SPICE netlist content
        """
        lines = []
        lines.append("* SPICE netlist generated by Dielectric")
        lines.append(f"* Board: {placement.board.name or 'board'}")
        lines.append("")
        
        # Components (simplified - would need component models)
        for comp_name, comp in placement.components.items():
            # Find nets connected to this component
            nets = []
            for net_name, net in placement.nets.items():
                for comp_ref, pad_name in net.pins:
                    if comp_ref == comp_name:
                        nets.append((net_name, pad_name))
            
            if len(nets) >= 2:
                # Create SPICE component line
                # Format: X<name> <net1> <net2> ... <model>
                net_list = " ".join(net[0] for net in nets[:2])
                lines.append(f"X{comp_name} {net_list} {comp.value or 'UNKNOWN'}")
        
        lines.append(".END")
        
        return "\n".join(lines)

